// Generated from Study Buddy src/custom-skills/shared/modelTaskCatalog.ts. Do not edit.
/** Canonical workflow task catalogue. Run scripts/sync-model-task-catalog.mjs after edits. */
export const STUDY_BUDDY_TASK_ROLES = {
  source_search: "contentAnalyzer",
  content_analyzer: "contentAnalyzer",
  content_repair: "contentAnalyzer",
  quiz_solver: "quizSolver",
  artifact_planner: "artifactPlanner",
  artifact_builder: "artifactBuilder",
  artifact_repair: "artifactBuilder",
  quality_reviewer: "qualityReviewer",
} as const;
export type StudyBuddyModelTask = keyof typeof STUDY_BUDDY_TASK_ROLES;

export const STUDY_BUDDY_MODEL_TASKS = [
  {
    id: "source_search",
    task: "source_search",
    role: "contentAnalyzer",
    inherits: "contentAnalyzer",
    label: "Source search",
    description: "Select and verify relevant source evidence.",
  },
  {
    id: "content_repair",
    task: "content_repair",
    role: "contentAnalyzer",
    inherits: "contentAnalyzer",
    label: "Content repair",
    description: "Repair invalid learning content; also supplies defaults for specialized repairs.",
  },
  {
    id: "artifact_repair",
    task: "artifact_repair",
    role: "artifactBuilder",
    inherits: "artifactBuilder",
    label: "Artifact repair",
    description: "Repair generated documents or pages.",
  },
  {
    id: "request_evaluation",
    task: "artifact_planner",
    role: "artifactPlanner",
    inherits: "artifact_planner",
    label: "Request evaluation",
    description: "Translate the request into a structured output contract.",
  },
  {
    id: "course_selection",
    task: "source_search",
    role: "contentAnalyzer",
    inherits: "source_search",
    label: "Course selection",
    description: "Shortlist courses and resolve the requested course from evidence.",
  },
  {
    id: "source_selection",
    task: "source_search",
    role: "contentAnalyzer",
    inherits: "source_search",
    label: "Source selection",
    description: "Choose relevant sources using semantic search.",
  },
  {
    id: "source_verification",
    task: "source_search",
    role: "contentAnalyzer",
    inherits: "source_search",
    label: "Source verification",
    description: "Check whether source evidence supports a selection.",
  },
  {
    id: "obligation_scope",
    task: "source_search",
    role: "contentAnalyzer",
    inherits: "source_search",
    label: "Obligation scope",
    description: "Extract course and time restrictions from a request.",
  },
  {
    id: "obligation_scope_review",
    task: "source_search",
    role: "contentAnalyzer",
    inherits: "source_search",
    label: "Obligation scope review",
    description: "Verify that a restriction represents the complete request.",
  },
  {
    id: "obligation_triage",
    task: "source_search",
    role: "contentAnalyzer",
    inherits: "source_search",
    label: "Activity triage",
    description: "Identify activities that are outside the requested obligation scope.",
  },
  {
    id: "obligation_exclusion_review",
    task: "source_search",
    role: "contentAnalyzer",
    inherits: "source_search",
    label: "Activity exclusion review",
    description: "Independently verify evidence before excluding an activity.",
  },
  {
    id: "obligation_classification",
    task: "source_search",
    role: "contentAnalyzer",
    inherits: "source_search",
    label: "Activity classification",
    description: "Classify activities and extract grounded obligation facts.",
  },
  {
    id: "source_planning",
    task: "artifact_planner",
    role: "artifactPlanner",
    inherits: "artifact_planner",
    label: "Source planning",
    description: "Plan evidence acquisition and coverage.",
  },
  {
    id: "content_extraction",
    task: "content_analyzer",
    role: "contentAnalyzer",
    inherits: "content_analyzer",
    label: "Content extraction",
    description: "Transform source material into structured chapter content.",
  },
  {
    id: "content_extraction_repair",
    task: "content_repair",
    role: "contentAnalyzer",
    inherits: "content_repair",
    label: "Content extraction repair",
    description: "Repair failed chapter extraction with validation feedback.",
  },
  {
    id: "learning_content",
    task: "content_analyzer",
    role: "contentAnalyzer",
    inherits: "content_analyzer",
    label: "Learning content",
    description: "Write explanations, examples and practice for a study guide.",
  },
  {
    id: "learning_content_repair",
    task: "content_repair",
    role: "contentAnalyzer",
    inherits: "content_repair",
    label: "Learning content repair",
    description: "Repair failed study-guide content.",
  },
  {
    id: "learning_progression",
    task: "content_analyzer",
    role: "contentAnalyzer",
    inherits: "content_analyzer",
    label: "Learning progression",
    description: "Plan learning stages and topic progression.",
  },
  {
    id: "learning_progression_repair",
    task: "content_repair",
    role: "contentAnalyzer",
    inherits: "content_repair",
    label: "Learning progression repair",
    description: "Repair an invalid learning progression.",
  },
  {
    id: "visual_planning",
    task: "artifact_planner",
    role: "artifactPlanner",
    inherits: "artifact_planner",
    label: "Visual planning",
    description: "Plan diagrams and supporting visual evidence.",
  },
  {
    id: "visual_selection",
    task: "content_analyzer",
    role: "contentAnalyzer",
    inherits: "content_analyzer",
    label: "Visual selection",
    description: "Select and interpret source visuals.",
  },
  {
    id: "visual_selection_repair",
    task: "content_repair",
    role: "contentAnalyzer",
    inherits: "content_repair",
    label: "Visual selection repair",
    description: "Repair failed visual-evidence interpretation.",
  },
  {
    id: "assessment_planning",
    task: "artifact_planner",
    role: "artifactPlanner",
    inherits: "artifact_planner",
    label: "Assessment planning",
    description: "Compose an assessment structure from evidence.",
  },
  {
    id: "solution_generation",
    task: "content_analyzer",
    role: "contentAnalyzer",
    inherits: "content_analyzer",
    label: "Solution generation",
    description: "Generate complete reference solutions for assessment tasks.",
  },
  {
    id: "solution_verification",
    task: "quality_reviewer",
    role: "qualityReviewer",
    inherits: "quality_reviewer",
    label: "Solution verification",
    description: "Independently check reference solutions for correctness.",
  },
  {
    id: "question_review",
    task: "quality_reviewer",
    role: "qualityReviewer",
    inherits: "quality_reviewer",
    label: "Question review",
    description: "Review question correctness, scope and answer quality.",
  },
  {
    id: "question_repair",
    task: "content_repair",
    role: "contentAnalyzer",
    inherits: "content_repair",
    label: "Question repair",
    description: "Repair only failed questions and their answers.",
  },
  {
    id: "document_build",
    task: "artifact_builder",
    role: "artifactBuilder",
    inherits: "artifact_builder",
    label: "Document building",
    description: "Build the printable document.",
  },
  {
    id: "document_repair",
    task: "artifact_repair",
    role: "artifactBuilder",
    inherits: "artifact_repair",
    label: "Document repair",
    description: "Repair a failed printable document.",
  },
  {
    id: "html_planning",
    task: "artifact_planner",
    role: "artifactPlanner",
    inherits: "artifact_planner",
    label: "Page planning",
    description: "Plan an interactive learning page.",
  },
  {
    id: "html_build",
    task: "artifact_builder",
    role: "artifactBuilder",
    inherits: "artifact_builder",
    label: "Page building",
    description: "Build interactive HTML.",
  },
  {
    id: "html_repair",
    task: "artifact_repair",
    role: "artifactBuilder",
    inherits: "artifact_repair",
    label: "Page repair",
    description: "Repair failed HTML or interactions.",
  },
  {
    id: "content_review",
    task: "quality_reviewer",
    role: "qualityReviewer",
    inherits: "quality_reviewer",
    label: "Content review",
    description: "Check extracted content and source coverage.",
  },
  {
    id: "pdf_review",
    task: "quality_reviewer",
    role: "qualityReviewer",
    inherits: "quality_reviewer",
    label: "PDF review",
    description: "Inspect the rendered document.",
  },
  {
    id: "html_review",
    task: "quality_reviewer",
    role: "qualityReviewer",
    inherits: "quality_reviewer",
    label: "Page review",
    description: "Review the completed interactive page.",
  },
  {
    id: "quiz_answer",
    task: "quiz_solver",
    role: "quizSolver",
    inherits: "quiz_solver",
    label: "Quiz answers",
    description: "Solve an observed quiz question.",
  },
  {
    id: "quiz_verification",
    task: "quiz_solver",
    role: "quizSolver",
    inherits: "quiz_solver",
    label: "Quiz verification",
    description: "Review a proposed quiz answer independently.",
  },
] as const;
export type StudyBuddyModelOperation = (typeof STUDY_BUDDY_MODEL_TASKS)[number]["id"];
export type StudyBuddyModelPolicyKey = StudyBuddyModelTask | StudyBuddyModelOperation;
