// @effect-diagnostics nodeBuiltinImport:off - Codex policy materialization is a Node boundary.
import { randomUUID } from "node:crypto";
import { chmod, mkdir, rename, writeFile } from "node:fs/promises";
import path from "node:path";

import { MINIMUM_STUDY_BUDDY_CODEX_VERSION } from "@t3tools/contracts";
import type { ServerConfigShape } from "../../config.ts";

export const STUDY_BUDDY_CODEX_PERMISSION_PROFILE = "study_buddy";
export const STUDY_BUDDY_CODEX_ANALYSIS_PERMISSION_PROFILE = "study_buddy_analysis";
export { MINIMUM_STUDY_BUDDY_CODEX_VERSION };

export interface StudyBuddyCodexPolicyPaths {
  readonly codexHome: string;
  readonly configPath: string;
  readonly deniedPaths: ReadonlyArray<string>;
}

function legacyCredentialRoot(config: ServerConfigShape): string {
  if (process.env.STUDY_BUDDY_ROOT) return path.resolve(process.env.STUDY_BUDDY_ROOT);
  if (process.env.STUDY_BUDDY_T3_ROOT) {
    return path.resolve(process.env.STUDY_BUDDY_T3_ROOT, "..");
  }
  return config.cwd;
}

export function resolveStudyBuddyCodexPolicyPaths(
  config: ServerConfigShape,
): StudyBuddyCodexPolicyPaths {
  const configuredHome = process.env.STUDY_BUDDY_CODEX_HOME?.trim();
  const codexHome = path.resolve(configuredHome || path.join(config.stateDir, "codex-home"));
  const credentialRoot = legacyCredentialRoot(config);
  return {
    codexHome,
    configPath: path.join(codexHome, "config.toml"),
    deniedPaths: [
      config.secretsDir,
      path.join(credentialRoot, ".env.local"),
      path.join(credentialRoot, ".env"),
    ],
  };
}

const tomlString = (value: string): string => JSON.stringify(value);

export function buildStudyBuddyCodexConfig(paths: StudyBuddyCodexPolicyPaths): string {
  const deniedPaths = [...new Set(paths.deniedPaths)];
  const absoluteRules = deniedPaths.map((entry) => `${tomlString(entry)} = "deny"`).join("\n");
  return `# Generated by Study Buddy. Changes are replaced during startup.
default_permissions = "${STUDY_BUDDY_CODEX_PERMISSION_PROFILE}"
approval_policy = "on-request"
web_search = "disabled"
allow_login_shell = false

[features]
default_mode_request_user_input = true

[permissions.${STUDY_BUDDY_CODEX_PERMISSION_PROFILE}]
description = "Study Buddy workspace access with credentials denied."
extends = ":workspace"

[permissions.${STUDY_BUDDY_CODEX_PERMISSION_PROFILE}.filesystem]
glob_scan_max_depth = 8
${absoluteRules}

[permissions.${STUDY_BUDDY_CODEX_PERMISSION_PROFILE}.filesystem.":workspace_roots"]
"**/.env" = "deny"
"**/.env.*" = "deny"
"**/credentials.json" = "deny"
"**/secrets.json" = "deny"
"**/*.credentials" = "deny"

[permissions.${STUDY_BUDDY_CODEX_PERMISSION_PROFILE}.network]
enabled = false

[permissions.${STUDY_BUDDY_CODEX_ANALYSIS_PERMISSION_PROFILE}]
description = "Read-only Study Buddy analysis with credentials denied."
extends = ":read-only"

[permissions.${STUDY_BUDDY_CODEX_ANALYSIS_PERMISSION_PROFILE}.filesystem]
glob_scan_max_depth = 8
${absoluteRules}

[permissions.${STUDY_BUDDY_CODEX_ANALYSIS_PERMISSION_PROFILE}.filesystem.":workspace_roots"]
"**/.env" = "deny"
"**/.env.*" = "deny"
"**/credentials.json" = "deny"
"**/secrets.json" = "deny"
"**/*.credentials" = "deny"

[permissions.${STUDY_BUDDY_CODEX_ANALYSIS_PERMISSION_PROFILE}.network]
enabled = false

[shell_environment_policy]
inherit = "core"
ignore_default_excludes = false
exclude = ["MOODLE_*", "CIS_*", "*PASSWORD*", "*PASSCODE*", "*TOKEN*", "*SECRET*", "*API_KEY*"]
`;
}

export async function ensureStudyBuddyCodexHome(
  config: ServerConfigShape,
): Promise<StudyBuddyCodexPolicyPaths> {
  const paths = resolveStudyBuddyCodexPolicyPaths(config);
  await mkdir(paths.codexHome, { recursive: true, mode: 0o700 });
  await chmod(paths.codexHome, 0o700).catch(() => undefined);
  const temporaryPath = `${paths.configPath}.${process.pid}.${randomUUID()}.tmp`;
  await writeFile(temporaryPath, buildStudyBuddyCodexConfig(paths), {
    encoding: "utf8",
    mode: 0o600,
  });
  await chmod(temporaryPath, 0o600).catch(() => undefined);
  await rename(temporaryPath, paths.configPath);
  await chmod(paths.configPath, 0o600).catch(() => undefined);
  return paths;
}

export function studyBuddyCodexEnvironment(
  paths: StudyBuddyCodexPolicyPaths,
  source: NodeJS.ProcessEnv = process.env,
): NodeJS.ProcessEnv {
  return {
    ...source,
    CODEX_HOME: paths.codexHome,
    STUDY_BUDDY_CODEX_HOME: paths.codexHome,
    STUDY_BUDDY_CODEX_PERMISSION_PROFILE: STUDY_BUDDY_CODEX_PERMISSION_PROFILE,
  };
}
